import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import dotenv from 'dotenv';

const envPath = resolve(process.cwd(), '.env');
dotenv.config({ path: envPath });

const apiBaseUrl = process.env.API_BASE_URL || '/api/v1';
const appEnv = process.env.APP_ENV || 'development';
const stripePublishableKey = process.env.STRIPE_PUBLISHABLE_KEY || '';

const outputPath = resolve(process.cwd(), 'src/app/config.generated.ts');
mkdirSync(dirname(outputPath), { recursive: true });
const contents = `// Auto-generated by scripts/generate-config.mjs\nexport const appConfig = {\n  apiBaseUrl: '${apiBaseUrl}',\n  appEnv: '${appEnv}',\n  stripePublishableKey: '${stripePublishableKey}'\n};\n`;
writeFileSync(outputPath, contents, 'utf8');
console.log(`Generated ${outputPath} with API_BASE_URL=${apiBaseUrl} APP_ENV=${appEnv}`);
